# -*- coding: utf-8 -*-
"""AnalisisExploratorioStack Overflow annual developer survey.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NpJYUx5tRj6C6MxYz5LZ1sTSfR5ANrOI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib

datos=pd.read_csv('survey_results_public.csv')

datos.head()

datos.info()

datos.isnull().sum()



"""**1. ¿Qué tipo de compañías son los que tienen el salario más alto?**"""

datos.groupby(['Industry']).agg({'ConvertedCompYearly':[np.sum]})

datos.groupby('Industry') ['ConvertedCompYearly'].sum()

datos.groupby('Industry') ['ConvertedCompYearly'].sum().sort_values(ascending=False).head(5)

graficatotalsalario= plt.figure(figsize=(15,10))
plt.title("Total salario al año")
(datos.groupby('Industry') ['ConvertedCompYearly'].sum()).sort_values(ascending=False).head(6).plot(kind="bar", alpha=0.5)

datos.head(5)

datos.info()

"""**¿Qué porcentaje del total representa el tipo de trabajo Remoto de los empleados? **



"""

datos['RemoteWork'].unique()

datos['RemoteWork'].value_counts()

graficatorta= plt.figure(figsize=(5,6))
plt.title("Tipo de Trabajo")
lista=datos['RemoteWork'].value_counts()
lista1= ['Remote', 'Hybrid (some remote, some in-person)', 'In-person']
plt.pie(lista, labels=lista1,  autopct="%0.1f %%" )
plt.axis("equal")
plt.show()

"""**Cómo afecta la experiencia de código con el salario**"""

datos.groupby('YearsCode') ['ConvertedCompYearly'].sum().sort_values(ascending=False).head(10)

graficabarras= plt.figure(figsize=(15,10))
plt.title("Años Codigo")
datos.groupby('YearsCode') ['ConvertedCompYearly'].sum().sort_values(ascending=False).head(10).plot(kind="bar", alpha=0.5)

datos['WorkExp']

datos['LearnCode'].value_counts().sort_values(ascending=False).head(5)

graficametodoestudio= plt.figure(figsize=(15,10))
plt.title("Metodo de estudio")
datos['LearnCode'].value_counts().sort_values(ascending=False).head(5).plot(kind="bar", alpha=0.5)

datos.groupby(['LearnCode']).count().sort_values(by='ResponseId',ascending=False).head(5)

"""**¿Es más probable que consigas un trabajo como desarrollador si tienes una maestría?**"""

datos['EdLevel'].value_counts()

datos.EdLevel.value_counts().plot(kind="bar")
plt.title("Cantidad de empleados por Grado Académico")
plt.show()